class Stack:
    def __init__(self, n):
        self.stack = []
        self.n = n
    
    def size(self):
        return(len(self.stack))
    
    def push(self, m):
        if self.size() < self.n:
            self.stack.append(m)
        else:
            print("Stack is full. Can not add " + str(m) + ".")

    def display(self):
        print(self.stack)

    def pop(self):
        stack = 1
        if stack <= self.size():
            self.stack.pop()
        else:
            print("Sorry, can't pop anymore.")

Star = Stack(10)
Star.push(24)
print(Star.size())
Star.display()
Star.push(48)
print(Star.size())
Star.display()
Star.push(72)
print(Star.size())
Star.display()
Star.push(96)
print(Star.size())
Star.display()
Star.push(120)
print(Star.size())
Star.display()
Star.push(144)
print(Star.size())
Star.display()
Star.push(168)
print(Star.size())
Star.display()
Star.push(192)
print(Star.size())
Star.display()
Star.push(216)
print(Star.size())
Star.display()
Star.push(240)
print(Star.size())
Star.display()
Star.pop()
print(Star.size())
Star.display()
Star.pop()
print(Star.size())
Star.display()
Star.pop()
print(Star.size())
Star.display()
Star.pop()
print(Star.size())
Star.display()
Star.pop()
print(Star.size())
Star.display()
Star.pop()
print(Star.size())
Star.display()
Star.pop()
print(Star.size())
Star.display()
Star.pop()
print(Star.size())
Star.display()
Star.pop()
print(Star.size())
Star.display()
Star.pop()
print(Star.size())
Star.display()
Star.push(24)
print(Star.size())
Star.display()
Star.push(48)
print(Star.size())
Star.display()
Star.push(72)
print(Star.size())
Star.display()
Star.push(96)
print(Star.size())
Star.display()
Star.push(120)
print(Star.size())
Star.display()
Star.push(144)
print(Star.size())
Star.display()
Star.push(168)
print(Star.size())
Star.display()
Star.push(192)
print(Star.size())
Star.display()
Star.push(216)
print(Star.size())
Star.display()
Star.push(240)
print(Star.size())
Star.display()